citadel_version: 4
metadata:
  name: ItchySats
  version: 0.7.0
  category: Finance
  tagline: Peer-2-peer derivatives on Bitcoin
  developers:
    ItchySats: https://itchysats.network
  permissions:
  - electrum
  repo:
    Public: https://github.com/itchysats/itchysats
  support: https://github.com/itchysats/itchysats/issues
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: "weareallsatoshi"
  torOnly: false
  description: |-
    ItchySats enables peer-2-peer CFD trading on Bitcoin using DLCs (discreet log contracts). No account needed, no trusted third-party - just you and your keys.

    This is beta software. We tested it on test- and mainnet, but there are no guarantees that it will always behave as expected.
    Please be mindful with how much money you trust the application with.
    CFDs trading is inherently risky, be sure to read up on it before using this application.

    That said: This is pretty awesome, go nuts!

    1. Fund the ItchySats wallet
    2. Open a position
    3. Monitor the price movement
    4. Profit

    Limitations of the mainnet beta:

    1. Minimum position quantity is $100, maximum $1000

    With 0.4.0 your CFDs are perpetual positions that are extended hourly. This means your CFD position will remain open forever unless you decide to close it. A funding fee is collected hourly when the CFD is extended.

    With 0.4.8 you can open long and short positions, previously only long positions were possible.

    With 0.5.0 you can chose from different from leverage. Leverage choices are configured by the maker and might initially be restricted to x1, x2 and x3.

    With 0.6.0 you can open positions on BTCUSD and ETHUSD prices. #ShortTheMerge

    With 0.7.0 we replaced basic authentication with cookie-based authentication. Password is not tied to app seed anymore; it has to be set up manually and backed up separately. Note: ItchySats wallet is still tied to the app seed.
services:
  main:
    image: ghcr.io/itchysats/itchysats/taker:0.7.0@sha256:0c29162897a6c2bc2093373306f920400a0718960e1e4b1d80bd44beb485a498
    stop_grace_period: 1m
    restart: on-failure
    command:
    - --app-seed=$APP_SEED_2
    - $BITCOIN_NETWORK
    - --electrum=tcp://$ELECTRUM_IP:$ELECTRUM_PORT
    environment:
      ITCHYSATS_ENV: citadel
    port: 8000
    mounts:
      data:
        data: /data
